### PR TITLE
Feature/crd humio view

### LINKED ISSUE #207: Feature Request: CRD for HumioViews
It would be awesome to be able to manage views in Humio through a custom resource, e.g. `HumioView`.

### PR DESCRIPTION
**Pull request by mahlunar**
Fixes #207 

### Added HumioView CRD
Name and Connections can now be set.
Description is omitted for now as we would need an update to the view [api](https://github.com/humio/cli/blob/master/api/views.go#L19)

#### Controller
Added support for adding, updating and deleting views

## Tests performed
I have run all tests via "make test".
I have also spun up a humio cluster via the hack tools and observed the changes to the humio views in the cluster.

Please let me know if anything is missing or should be changed.

### CODE REVIEW

**Comment by mahlunar** [comment]
I can see that the e2e tests are failing where running make test works. 

I will gladly accept some hints on how to proceed 👍

**Comment by kaspernissen** [comment]
I just had a look at the failing test, it looks like it's failing because the Humio View test tries to create a repository that already exists. We should change the `repositoryKey` and `repositoryToCreate` resources to be unique so that it doesn't conflict with the repository test.

```
Humio Resources Controllers Humio View 
  Should handle view correctly
  /home/runner/work/humio-operator/humio-operator/controllers/humioresources_controller_test.go:343
STEP: Creating a shared humio cluster if it doesn't already exist
STEP: Creating the repository successfully

• Failure [0.008 seconds]
Humio Resources Controllers
/home/runner/work/humio-operator/humio-operator/controllers/humioresources_controller_test.go:35
  Humio View
  /home/runner/work/humio-operator/humio-operator/controllers/humioresources_controller_test.go:342
    Should handle view correctly [It]
    /home/runner/work/humio-operator/humio-operator/controllers/humioresources_controller_test.go:343

    Expected success, but got an error:
        <*errors.StatusError | 0xc000f4aa00>: {
            ErrStatus: {
                TypeMeta: {Kind: "", APIVersion: ""},
                ListMeta: {
                    SelfLink: "",
                    ResourceVersion: "",
                    Continue: "",
                    RemainingItemCount: nil,
                },
                Status: "Failure",
                Message: "humiorepositories.core.humio.com \"humiorepository\" already exists",
                Reason: "AlreadyExists",
                Details: {
                    Name: "humiorepository",
                    Group: "core.humio.com",
                    Kind: "humiorepositories",
                    UID: "",
                    Causes: nil,
                    RetryAfterSeconds: 0,
                },
                Code: 409,
            },
        }
        humiorepositories.core.humio.com "humiorepository" already exists

    /home/runner/work/humio-operator/humio-operator/controllers/humioresources_controller_test.go:389
```

**Comment by Crevil** [comment]
Ah, that should be an easy fix. Will you go ahead or should I @kaspernissen ?

**Comment by kaspernissen** [comment]
I think I might have it. `make test` succeeds locally (it also did in the initial version, so no guarantee), let's see if e2e succeeds here as well 🙏

**Comment by kaspernissen** [comment]
Unfortunately, didn't fix the failing test. We found the issue, which seems to be an addition in the cli package, that now results in the expectation to not match; https://github.com/humio/cli/blame/dea38288df5de0e5e4c52a049207b7322ba1bc4c/api/repositories.go#L15

@mahlunar is working on a fix.

**Comment by mahlunar** [comment]
Fixed. The Repository Id was the culprit which failed on assertions. I have added a new struct in the test file that excludes the Id field. Let me know if this is ok.

**Review by SaaldjorMike — COMMENTED** [review]
LGTM. The only comment I have is that you need to make sure to incorporate the latest changes on master and regenerate the CRD manifests. That is because we are now using a slightly newer controller-gen version, and I'd much prefer if we have all CRD files generated based on the same version.

To generate the CRD's again, you have to remove the old controller-gen binary and then generate the CRD manifests. Generating CRD manifests will automatically grab the controller-gen version but currently it does not handle updates to it that well. So this would be what you need to do after incorporating the latest changes on master:
```
rm ~/go/bin/controller-gen
make manifests
```
Then add the updated CRD files to this PR. After that we should be ready to go.

Thank you so much for this contribution, it is much appreciated!

**Review by SaaldjorMike — APPROVED** [review]
LGTM.

**Comment by mahlunar** [comment]
Rebase done and updated manifests.

**Review by SaaldjorMike — APPROVED** [review]

**Review by jswoods — APPROVED** [review]

**Pull request merged**
