### PR TITLE
Add option to configure disabling automatic search in repos/views

### LINKED ISSUE #693: setAutomaticSearching on Repository creation
Is it possible to get the option to disable Auto Searching on Repository creation? The GraphQL mutation is:

mutation {
  setAutomaticSearching(name: ["View, or, Repo Name"], automaticSearch: false) {
    __typename
  }
}

### PR DESCRIPTION
**Pull request by brads-au**
This change:

- Adds the `DisableAutomaticSearch` field to the spec of HumioRepository and HumioView
- Adds the `Description` field to the spec of HumioView
- Resolves #693 

Notes:

I decided to inverse the Automatic Search option to `DisableAutomaticSearch`, that way by default the bool has it's default `false` value, and the repo/view maintains it's `true` value if this field is not specified.

Requires:

- cli PR: https://github.com/humio/cli/pull/163

### CODE REVIEW

**Comment by SaaldjorMike** [comment]
I created https://github.com/humio/humio-operator/pull/815 which also bumps the dependency, which we can also use to see if tests pass with this change.

**Comment by SaaldjorMike** [comment]
Seems like even with your change and updated dependency as I tried in #815 tests seem to fail with:
```
2024-06-26T08:33:39.9150010Z   [FAILED] in [It] - /var/src/controllers/suite/resources/humioresources_controller_test.go:496 @ 06/26/24 08:33:39.393
2024-06-26T08:33:39.9151130Z   << Timeline
2024-06-26T08:33:39.9151379Z 
2024-06-26T08:33:39.9151664Z   [FAILED] Timed out after 300.001s.
2024-06-26T08:33:39.9152147Z   Expected
2024-06-26T08:33:39.9152502Z       <api.View>: {
2024-06-26T08:33:39.9153032Z           Name: "example-view",
2024-06-26T08:33:39.9153549Z           Description: "",
2024-06-26T08:33:39.9154017Z           Connections: [
2024-06-26T08:33:39.9154441Z               {
2024-06-26T08:33:39.9155159Z                   RepoName: "example-repository-view",
2024-06-26T08:33:39.9155826Z                   Filter: "*",
2024-06-26T08:33:39.9156386Z               },
2024-06-26T08:33:39.9156746Z           ],
2024-06-26T08:33:39.9157181Z           AutomaticSearch: true,
2024-06-26T08:33:39.9157629Z       }
2024-06-26T08:33:39.9157920Z   to equal
2024-06-26T08:33:39.9158270Z       <api.View>: {
2024-06-26T08:33:39.9158784Z           Name: "example-view",
2024-06-26T08:33:39.9159293Z           Description: "",
2024-06-26T08:33:39.9159761Z           Connections: [
2024-06-26T08:33:39.9160179Z               {
2024-06-26T08:33:39.9160898Z                   RepoName: "example-repository-view",
2024-06-26T08:33:39.9161564Z                   Filter: "*",
2024-06-26T08:33:39.9162012Z               },
2024-06-26T08:33:39.9162368Z           ],
2024-06-26T08:33:39.9162803Z           AutomaticSearch: false,
2024-06-26T08:33:39.9163248Z       }
2024-06-26T08:33:39.9164196Z   In [It] at: /var/src/controllers/suite/resources/humioresources_controller_test.go:496 @ 06/26/24 08:33:39.393
```

**Comment by brads-au** [comment]
Thanks @SaaldjorMike. I'll take another look at this later today. It looks like due to the different field names "AutomaticSearch" in the CLI, and "DisableAutomaticSearch" in the CRD.

That got me thinking about the bool value as well, as it will currently default to false, which would enforce change onto any operator managed repo, which may or may not be what some people want.

I might have a look at using a separate type instead to handle the value and allow it to be null/un-managed.

**Comment by SaaldjorMike** [comment]
If you want, you could make them pointers, and so you'd know if they are actually explicitly set by the user or not:

From the current:
```
// DisableAutomaticSearch is used to disable the start search automatically on loading the search page option.
DisableAutomaticSearch bool `json:"disableAutomaticSearch,omitempty"`
```
To this:
```
// DisableAutomaticSearch is used to disable the start search automatically on loading the search page option.
DisableAutomaticSearch *bool `json:"disableAutomaticSearch,omitempty"`
```
then you know if e.g. DisableAutomaticSearch is not not that the user explicitly set it to either true or false. 

But if you do, then you might as well just go with:
```
// AutomaticSearch is used to set the start search automatically on loading the search page option.
AutomaticSearch *bool `json:"automaticSearch,omitempty"`
```
since you no longer rely on the empty value of that bool.

**Comment by brads-au** [comment]
Thanks @SaaldjorMike, good idea. I've changed them over to pointers now and including a BoolTrue function in the helpers package. Also added a couple line to the tests which should resolve those issues. Cheers.

**Comment by SaaldjorMike** [comment]
The diff seems to be showing a lot of unrelated things to this PR, things that was introduced on master. Maybe we could get that cleaned up a bit, then I can kick off a round of tests, and once green, we can look at getting it merged in.

**Comment by brads-au** [comment]
Alright, I fixed that up. You should be good to kick off the tests @SaaldjorMike.

Note to self: watch what you rebase. :)

**Review by SaaldjorMike — APPROVED** [review]

**Pull request merged**
