### PR TITLE
Fix bug where service account secrets are not created when using custom service accounts and add tests

### PR DESCRIPTION
**Pull request by jswoods**
Fixes part of https://github.com/humio/humio-operator/issues/163.

### CODE REVIEW

**Review by SaaldjorMike — APPROVED** [review]
LGTM. Could you perhaps remove the old disabled/broken test that touches on this topic? https://github.com/humio/humio-operator/blob/master/controllers/humiocluster_controller_test.go#L572-L617

**Comment by SaaldjorMike** [comment]
Also @jswoods, it looks like e2e failed with this:
```
• Failure [306.062 seconds]
HumioCluster Controller
/home/runner/work/humio-operator/humio-operator/controllers/humiocluster_controller_test.go:43
  Humio Cluster With Custom Service Accounts
  /home/runner/work/humio-operator/humio-operator/controllers/humiocluster_controller_test.go:1382
    Creating cluster with custom service accounts [It]
    /home/runner/work/humio-operator/humio-operator/controllers/humiocluster_controller_test.go:1383

    Timed out after 300.000s.
    Expected
        <[]v1.Pod | len:0, cap:0>: []
    to have length 1

    /home/runner/work/humio-operator/humio-operator/controllers/humiocluster_controller_test.go:1459
```

We would need to fix that before merging this.

**Comment by jswoods** [comment]
Converting to draft until I can fix the tests.

**Comment by jswoods** [comment]
Tests have been fixed.

**Review by SaaldjorMike — APPROVED** [review]

**Pull request merged**
