### PR TITLE
Add support for custom labels to humio service

### PR DESCRIPTION
**Pull request by kaspernissen**
This PR adds functionality to add custom labels to the humio service created by the humio-operator.

Services like `linkerd` multicluster looks for a specific label to mirror services to multiple clusters. 

I have added it to the `HumioCluster` resource as `HumioServiceLabels`. It may be a good idea in a future PR to nest these specific `Service` configurations under a top-level `service` object or similar, as you already do with ingress.

### CODE REVIEW

**Comment by jswoods** [comment]
Thanks @kaspernissen! This looks good to me. The only thing - do you mind squashing the commits?

**Comment by kaspernissen** [comment]
Thanks @jswoods! Isn't squash merging this to master sufficient using the Github functionality - or do you want me to squash merge locally and force push using rebase (then I'll start googling) ?

**Comment by jswoods** [comment]
@kaspernissen tbh, I haven't never used that but I will try it out! Usually on our team we squash first and then just do a plain merge from github :). But sounds like it should achieve the same goal.

**Review by jswoods — APPROVED** [review]

**Comment by kaspernissen** [comment]
Haha, tbh, I have never done it the other way around 🙈 Let me know if you want me to give a go locally.

**Pull request merged**
